### ISSUE TITLE
Scala Steward

### ISSUE THREAD

**Issue by IvanDyachenko** [IvanDyachenko/marketplace-scraper#27]
[🤖 A bot that helps you keep your Scala projects up-to-date](https://github.com/scala-steward-org/scala-steward)

Add `scala-steward.yml` to `.github/workflows`:
```yml
# This workflow will launch at 00:00 every Sunday
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
```
